[package]
name = "what-s-in-my-fridge"
version = "0.1.0"
authors = ["Daniel Filipe Nunes Silva <danielementary@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
